name: Trigger auto deployment for mei-acr

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mei-acr-AutoDeployTrigger-c307b0f4-de2b-4ca9-9d37-bee6a14a791b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MEIACR_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MEIACR_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MEIACR_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: cindy01.azurecr.io
          registryUsername: ${{ secrets.MEIACR_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MEIACR_REGISTRY_PASSWORD }}
          containerAppName: mei-acr
          resourceGroup: mei-env1
          imageToBuild: cindy01.azurecr.io/mei-acr:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


